<?php

namespace RuchJow\FeedbackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends EntityRepository
{

}
