<?php

namespace RuchJow\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PreSignedUserDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreSignedUserDataRepository extends EntityRepository
{
}
