<?php

namespace RuchJow\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JowEventRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class JowEventRepository extends EntityRepository
{
}
