<?php

namespace RuchJow\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskStatusRepository extends EntityRepository
{
}
