<?php

namespace RuchJow\MessagesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use RuchJow\UserBundle\Entity\User;

/**
 * FolderRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository
{

    /**
     * @param User $user
     * @param      $name
     *
     * @return Folder
     */
    public function findByOwnerAndName(User $user, $name)
    {
        return $this->findOneBy(array('owner' => $user, 'name' => $name));
    }

    /**
     * @param User $user
     *
     * @return Folder[]
     */
    public function findByOwner(User $user)
    {
        return $this->findBy(array('owner' => $user));
    }
}
