<?php

namespace RuchJow\MessagesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use RuchJow\UserBundle\Entity\User;

/**
 * MessageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

    /**
     * @param User $owner
     * @param      $folderName
     * @param      $start
     * @param      $limit
     *
     * @return Message[]
     */
    public function findByFolderLimited(User $owner, $folderName, $start, $limit)
    {
        $qb = $this->createQueryBuilder('m');

        $qb->join('m.folder', 'f')
            ->join('m.owner', 'u')
            ->where($qb->expr()->eq('u.id', ':userId'))
            ->setParameter('userId', $owner->getId())
            ->andWhere($qb->expr()->eq('f.name', ':folderName'))
            ->setParameter('folderName', $folderName)
            ->setFirstResult($start)
            ->setMaxResults($limit)
            ->orderBy('m.sentAt', 'desc');

        return $qb->getQuery()->getResult();
    }
}
