<?php

namespace RuchJow\MessagesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use RuchJow\UserBundle\Entity\User;

/**
 * ThreadRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends EntityRepository
{

    /**
     * @param ThreadsParent $parent
     * @param User          $user
     *
     * @return Thread
     */
    public function findByParentAndOwner(ThreadsParent $parent, User $user)
    {
        return $this->findOneBy(array('threadsParent' => $parent, 'owner' => $user));
    }
}
