<?php

namespace RuchJow\MessagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThreadsParentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ThreadsParentRepository extends EntityRepository
{
}
