<?php

namespace RuchJow\TerritorialUnitsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCodeRepository extends EntityRepository
{

    /**
     * @param $code
     *
     * @return null|PostCode
     */
    public function findOneByCode($code) {
        $id = (int) str_replace('-', '', $code);

        return $this->find($id);
    }

}
